version: '3.9'

services:  
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - network

  back:
    build: ./backend
    command: sh -c "cd Database && dotnet ef database update -v --no-color --no-build "
    networks:
      - network
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - .env

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - back
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db: