name: Deploy Site

on:
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Build the stack
        run: docker-compose up -d

  connect:
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /bank-core
            docker-compose stop
            git pull
            docker-compose up